openapi: 3.0.3
info:
  title: Communications outbound integration
  description: Send information to a user through different communication channels.
  version: '1.0.1'
  x-icon: phone_in_talk
servers:
  - description: Prism mock server
    url: 'http://localhost:4010'
tags:
  - name: communications-outbound-integration
paths:
  /service-api/v1/communications/batches:
    summary: Batch
    description: Sends a batch of communications to users
    post:
      tags:
        - communications-outbound-integration
      summary: Send batch.
      description: Send batch
      operationId: postBatches
      requestBody:
        description: Send batch
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchResponse'
            examples:
              postBatches:
                $ref: '#/components/examples/postBatches'
      responses:
        '202':
          description: Sent(offline)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchPostResponseBody'
              examples:
                batchPostResponseBody:
                  $ref: '#/components/examples/batchPostResponseBody'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              examples:
                badRequestError:
                  $ref: '#/components/examples/notFoundError'
components:
  schemas:
    BatchPostResponseBody:
      required:
        - communicationBatchId
      type: object
      properties:
        communicationBatchId:
          maxLength: 255
          type: string
          description: Id of the batch
        statuses:
          type: array
          items:
            $ref: '#/components/schemas/Status'
      description: 'Response object for batch send request, that contains info about status of message'
    BatchResponse:
      required:
        - recipients
        - content
      type: object
      properties:
        recipients:
          type: array
          items:
            $ref: '#/components/schemas/Recipient'
        content:
          type: array
          items:
            $ref: '#/components/schemas/Content'
      description: Batch of communications
    Content:
      required:
        - body
        - contentId
      type: object
      properties:
        contentId:
          maxLength: 255
          type: string
          description: Id of the content
        body:
          type: string
          description: Body of the message that can be template like
        title:
          type: string
          description: A title for the message
      description: Content of the message
    Error:
      type: object
      properties:
        code:
          maxLength: 255
          type: string
          description: Code of a error
        message:
          type: string
          description: Message of the error
      description: Error object for unsuccessful communication sent
    Recipient:
      type: object
      properties:
        ref:
          maxLength: 255
          type: string
          description: Reference number of the recipient
        to:
          type: array
          items:
            maxLength: 255
            type: string
            description: 'Representation of recipient address (e.g. email, phone or any other to receive the message)'
        from:
          maxLength: 255
          type: string
          description: Sender info
        contentId:
          maxLength: 255
          type: string
          description: Id of the contend for message
        data:
          type: object
          additionalProperties:
            type: string
          description: A collection of data objects to be used to fill the templates of the messages
      description: Recipient
      required:
        - contentId
        - data
        - ref
        - to
    Status:
      required:
        - ref
        - status
      type: object
      properties:
        ref:
          maxLength: 255
          type: string
          description: Reference number of the status
        status:
          maxLength: 255
          type: string
          description: String representation of status of the batch
        error:
          $ref: '#/components/schemas/Error'
      description: Status of the batch
    ErrorItem:
      title: ErrorItem
      type: object
      properties:
        message:
          description: Any further information.
          type: string
        key:
          description: '{capability-name}.api.{api-key-name}. For generated validation errors this is the path in the document the error resolves to. e.g. object name + ''.'' + field'
          type: string
        context:
          description: Context can be anything used to construct localised messages.
          type: object
          additionalProperties:
            type: string
    BadRequestError:
      title: BadRequestError
      type: object
      properties:
        message:
          description: Any further information
          type: string
        errors:
          description: Detailed error information
          type: array
          items:
            $ref: '#/components/schemas/ErrorItem'
      required:
        - message
  examples:
    status:
      value:
        statuses:
          - ref: '1'
            status: sent
          - ref: '2'
            status: pending
    recipient:
      value:
        recipients:
          - ref: '1'
            to:
              - 'voice:+441234567890'
            from: '+442222333444'
            contentId: '1'
            data:
              name: Timmy
              code: '654321'
          - ref: '2'
            to:
              - 'email:tina@example.com'
              - 'email:otheraddress@example.com'
            from: support@mybank.com
            contentId: '2'
            data:
              name: Tina
          - ref: '3'
            to:
              - 'email:tanya@example.com'
            from: '+442222333444'
            contentId: '2'
            data:
              name: Tanya
    error:
      value:
        error:
          code: '404'
          message: 'Unknown recipient: tanya@example.com'
    content:
      value:
        content:
          - contentId: '1'
            body: 'This is a message for communications-outbound-integration-api. Your code is: ${code}'
          - contentId: '2'
            title: Special offer
            body: 'Hi communications-outbound-integration-api, as a highly valued customer, we have a special loan rate for you! Click http://.... to redeem this offer before the end of lunch time!'
    postBatches:
      value:
        recipients:
          - ref: '1'
            to:
              - 'voice:+441234567890'
            from: '+442222333444'
            contentId: '1'
            data:
              name: Timmy
              code: '654321'
          - ref: '2'
            to:
              - 'email:tina@example.com'
              - 'email:otheraddress@example.com'
            from: support@mybank.com
            contentId: '2'
            data:
              name: Tina
          - ref: '3'
            to:
              - 'email:tanya@example.com'
            from: '+442222333444'
            contentId: '2'
            data:
              name: Tanya
        content:
          - contentId: '1'
            body: 'This is a message for communications-outbound-integration-api. Your code is: ${code}'
          - contentId: '2'
            title: Special offer
            body: 'Hi communications-outbound-integration-api, as a highly valued customer, we have a special loan rate for you! Click http://.... to redeem this offer before the end of lunch time!'
    batchPostResponseBody:
      value:
        communicationBatchId: abc123
        statuses:
          - ref: '1'
            status: sent
          - ref: '2'
            status: pending
          - ref: '3'
            status: failed
            error:
              code: '404'
              message: 'Unknown recipient: tanya@example.com'
    notFoundError:
      value:
        message: Resource not found.
        errors:
          - message: 'Unable to find the resource requested resource: {resource}.'
            key: common.api.resource
            context:
              resource: aResource
    badRequestError:
      value:
        message: Bad Request
        errors:
          - message: 'Value Exceeded. Must be between {min} and {max}.'
            key: common.api.shoesize
            context:
              max: '50'
              min: '1'
